title: "Aïssata Raoufa Touré"
logo: "/assets/images/photo raoufa ia.jpeg" # chemin vers ton logo ou photo de profil
description: "Portfolio Data Analyst | Orange Côte d’Ivoire | Passionnée de Data & Stratégie"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
